# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_sizemd
    - CONFIG=osx_sizesm

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j5yaeIQyq6bVcLYRRtMOH+IjSYoZTTqLBfJ8E2FnJBC2Us+eglR+75+55Na4NAyT4bLtPWRpZE7oLLO4qn/Lg+WQAh/04WMP3thg0wCJemQd79dw9c7tyYbqGe5yHEmrLotnBg0N46xA/C0oLO0q9W4zJyMo0X3+aMdl+YXSuNI/Q3d3Ob/cGTksqE5xw+A3mkQBm5gR+/KrJYdHtO11IJwvdRABVHiDyieXNusYbcntX3qft1raWAO9qC7LrD2cd90CMNFR9ZohYA+dCTVghJDESWppMoj1Ewo/bnHq060A82kribsuTPFR5/wK3DV9iDjsuU/kskRUCQBdzmEnKIdEHyLrT1jCZv88DI2aNz4BOjlW42FZYSd/8jzGsMC6GH3I7QmCG8UMHNdPGY2a2N4q/m1WvboINVgfqguG1rp7zyhL5J6okRndRfO6PhZ4Emt0HFbV8leyslnt5nYgDHJRat8Lk0dvzUYQ4TxERDYtUXRhIwJHGPF3yucvsGT2Ad5cDWpIs+ND4PtRCVK8gFSDkNw6keeNpjS+vCU9Ies87/v7S/htuPinevsq5Oc1UbXgKZLsC/KlJCn2/jh79Tqp+v94zccAFiaOJmlM6TXZoCK2Z+Be6ySPA9LHv0+TeQFzqK8NY0zkOZQ/OI98jH4QeloKzXNNOl46kaKKvz0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml