# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_sizemd
    - CONFIG=osx_sizesm

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "eJcBxGIIW3WZ8j51FExXdyKEN/GL/24XPU/R5Qu5GxGAstzoEzdUwCixf59QJkwwUPMArRR7NTRxznn5y3kXA97fz07WDADDMJurDO3T9ETx8inlDZ4kTZFXQoYxZx9/kR4coSj0dLge3JNB5PAkHgmE0LybPNYKOjbTRBo8HvjlkKWwl2GIg5cEFD7jUTuAvjJdSs5HSWqrOnP7kranBnLAFhSC0LMlpettM4r6kH+J70olAjBIMyLYLskwZrzvtqTqTybweAB9BMozB0GIqVzozzMLuVTb3wRqvURuFMJEWNCiXzdEv2LdIaBrdyhaus+fKOtgrDIl43LvTuIgmt0gMT0NscmGhMtbC2d3m0x/sqdiBpj4z85SEms5dCeDtMO0tvakCyuV5sgZ1iJjSC5slECwp+xVC1ot1vdewq/1vLOaCLWLVSzKDOBm5hYEu1UhvfIOEqkuDfV1ABa+wAZZQFNAE1+MmWg8iosmrkMXcpY9E6JSs0MqXf0k6RIEydunqRSjz33NNGUhiR+lr2zprsK29WutYWj/gWlFeASwFnNiyhdL9ZbiRFMaI3PlVHSV3eesz08/vHm7IkPAdO5buQ/iTbUIaH/Y2XehOEEgFO5hmq55rncgr0r61n3Vkxslc2wePVtEQ6qm+8BXPFkWmyuqqpkud9yHdbLjMJY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml