travis:
  secure:
    BINSTAR_TOKEN: eJcBxGIIW3WZ8j51FExXdyKEN/GL/24XPU/R5Qu5GxGAstzoEzdUwCixf59QJkwwUPMArRR7NTRxznn5y3kXA97fz07WDADDMJurDO3T9ETx8inlDZ4kTZFXQoYxZx9/kR4coSj0dLge3JNB5PAkHgmE0LybPNYKOjbTRBo8HvjlkKWwl2GIg5cEFD7jUTuAvjJdSs5HSWqrOnP7kranBnLAFhSC0LMlpettM4r6kH+J70olAjBIMyLYLskwZrzvtqTqTybweAB9BMozB0GIqVzozzMLuVTb3wRqvURuFMJEWNCiXzdEv2LdIaBrdyhaus+fKOtgrDIl43LvTuIgmt0gMT0NscmGhMtbC2d3m0x/sqdiBpj4z85SEms5dCeDtMO0tvakCyuV5sgZ1iJjSC5slECwp+xVC1ot1vdewq/1vLOaCLWLVSzKDOBm5hYEu1UhvfIOEqkuDfV1ABa+wAZZQFNAE1+MmWg8iosmrkMXcpY9E6JSs0MqXf0k6RIEydunqRSjz33NNGUhiR+lr2zprsK29WutYWj/gWlFeASwFnNiyhdL9ZbiRFMaI3PlVHSV3eesz08/vHm7IkPAdO5buQ/iTbUIaH/Y2XehOEEgFO5hmq55rncgr0r61n3Vkxslc2wePVtEQ6qm+8BXPFkWmyuqqpkud9yHdbLjMJY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
