travis:
  secure:
    BINSTAR_TOKEN: j5yaeIQyq6bVcLYRRtMOH+IjSYoZTTqLBfJ8E2FnJBC2Us+eglR+75+55Na4NAyT4bLtPWRpZE7oLLO4qn/Lg+WQAh/04WMP3thg0wCJemQd79dw9c7tyYbqGe5yHEmrLotnBg0N46xA/C0oLO0q9W4zJyMo0X3+aMdl+YXSuNI/Q3d3Ob/cGTksqE5xw+A3mkQBm5gR+/KrJYdHtO11IJwvdRABVHiDyieXNusYbcntX3qft1raWAO9qC7LrD2cd90CMNFR9ZohYA+dCTVghJDESWppMoj1Ewo/bnHq060A82kribsuTPFR5/wK3DV9iDjsuU/kskRUCQBdzmEnKIdEHyLrT1jCZv88DI2aNz4BOjlW42FZYSd/8jzGsMC6GH3I7QmCG8UMHNdPGY2a2N4q/m1WvboINVgfqguG1rp7zyhL5J6okRndRfO6PhZ4Emt0HFbV8leyslnt5nYgDHJRat8Lk0dvzUYQ4TxERDYtUXRhIwJHGPF3yucvsGT2Ad5cDWpIs+ND4PtRCVK8gFSDkNw6keeNpjS+vCU9Ies87/v7S/htuPinevsq5Oc1UbXgKZLsC/KlJCn2/jh79Tqp+v94zccAFiaOJmlM6TXZoCK2Z+Be6ySPA9LHv0+TeQFzqK8NY0zkOZQ/OI98jH4QeloKzXNNOl46kaKKvz0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
